on: push
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cross
        run: cargo install cross
      - name: Build
        run: cross build --target ${{ matrix.target }}
        env:
          # build for all targets
          matrix: ${{ fromJson(needs.clippy_check.outputs.matrix) }}