on: push
name: Build

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cargo install cross
      - name: Build binaries
        run: cross build --target ${{ matrix.target }} --release
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: rustberry-poe-monitor-${{ matrix.target == 'aarch64-unknown-linux-gnu' && 'aarch64' || 'armv7l' }}
          path: target/${{ matrix.target }}/release/rustberry-poe-monitor
